// <auto-generated />
using APIEstudoProj.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIEstudoProj.Data.Migrations
{
    [DbContext(typeof(APIEstudoProjContexto))]
    partial class APIEstudoProjContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAluno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Login")
                        .HasColumnType("int");

                    b.Property<string>("NomeAluno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Login");

                    b.ToTable("tb_Aluno");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<double>("Nota1")
                        .HasColumnType("float");

                    b.Property<double>("Nota2")
                        .HasColumnType("float");

                    b.Property<double>("NotaRecuperacao")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Id_Aluno");

                    b.ToTable("tb_Avaliacao");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Aluno");

                    b.ToTable("tb_Endereco");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Perfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tb_Login");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Aluno")
                        .HasColumnType("int");

                    b.Property<string>("Serie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Aluno");

                    b.ToTable("tb_Nivel");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailProfessor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_login")
                        .HasColumnType("int");

                    b.Property<string>("NomeProfessor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_login");

                    b.ToTable("tb_Professor");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Responsavel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailReponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_ALuno")
                        .HasColumnType("int");

                    b.Property<string>("NomeResponsavel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_ALuno");

                    b.ToTable("tb_Responsavel");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_Turma")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSala")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Turma");

                    b.ToTable("tb_Sala");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_ALuno")
                        .HasColumnType("int");

                    b.Property<string>("NomeTurma")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id_ALuno");

                    b.ToTable("tb_Turma");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Aluno", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Login", "Login")
                        .WithMany()
                        .HasForeignKey("Id_Login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Avaliacao", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Endereco", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Nivel", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Id_Aluno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Professor", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Login", "Login")
                        .WithMany()
                        .HasForeignKey("Id_login")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Login");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Responsavel", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Id_ALuno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Sala", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("Id_Turma")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("APIEstudoProj.Dominio.Dominio.Turma", b =>
                {
                    b.HasOne("APIEstudoProj.Dominio.Dominio.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("Id_ALuno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
